# a base image based with the basics:
#   - bash-completion
#   - tmux
#   - git
#   - vim

FROM ubuntu:trusty

MAINTAINER Ivo Jimenez <ivo.jimenez@gmail.com>

# install basic packages
RUN apt-get update && \
    apt-get install -yq bash-completion tmux git vim && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# add group and user for host's USER user, and add user to sudoers
ADD add_user.sh /root/add_user.sh
RUN /root/add_user.sh {USRID} {GRPID} {USER} && rm /root/add_user.sh && \
    echo "{USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/{USER} && \
    chmod 0440 /etc/sudoers.d/{USER}

ENV HOME /home/{USER}
WORKDIR /home/{USER}
CMD ["bash", "-l"]
USER {USER}

# below we assume that the built image is called 'mybase', i.e. was built like:
#
#   cd mybase
#   docker build -t ivotron:mybase .

# Once this base image is ready, we run it with:
#
#   docker run --rm -ti -v /path/to/home/:/home/{USER}:rw mybase
#
# for non-native scenarios (OSX), above we assume that /path/to/home is shared
# over NFS from the host to the guest VM (where docker runs in)
