#!/bin/bash

# check if cpp exists
command -v sed >/dev/null 2>&1 || { echo >&2 "I require sed but it's not installed.  Aborting."; exit 1; }

sed -e "s/{USER}/${USER}/g" -e "s/{GRPID}/`id -g $USER`/g" -e "s/{USRID}/`id -u $USER`/g" Dockerfile.in > Dockerfile
