# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "redodev" do |v|
    v.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "/Users/ivo/machines/coreos/Vagrantfile"
      d.vagrant_machine = "coreos"

      d.name = 'redodev'
      d.image = "ivotron:redodev"
      #d.build_dir = "."
      #d.build_args = ["--tag=ivotron:redodev"]

      d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
      #d.create_args = ["--memory=8589934592"]
      d.volumes = ["/home/ivo:/home/ivo:rw", "/Volumes/hdd/z:/Volumes/hdd/z:rw"]

      d.has_ssh = true
    end
    v.ssh.port = 22
    v.ssh.username = 'ivo'
    v.ssh.private_key_path = "~/.ssh/id_dsa"
    v.ssh.forward_agent = true
    v.nfs.functional = false
    #v.vm.synced_folder ".", "/vagrant", type: "nfs", :nfs_export => false
  end
end
