Vagrant.configure("2") do |config|
  config.vm.define "cephdev" do |v|
    v.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "/Users/ivo/machines/coreos/Vagrantfile"
      d.vagrant_machine = "coreos"

      d.name = 'cephdev'
      #d.image = "ivotron:cephdev"
      d.build_dir = "."
      d.build_args = ["--tag=ivotron:cephdev"]

      d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
      #d.create_args = ["--memory=8589934592"]
      d.volumes = ["/home/ivo:/home/ivo:rw", "/Volumes/hdd/z:/Volumes/hdd/z:rw"]

      d.has_ssh = true
    end
    v.ssh.port = 22
    v.ssh.username = 'ivo'
    v.ssh.private_key_path = "~/.ssh/id_dsa"
    v.ssh.forward_agent = true
  end
end
